name: Release Subtree

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_URL: 'https://github.com/otton-faros/hello-world-kedro.git'
      with:
        repository: otton-faros/submodule_repo
        event: sync_submod
        github_pat: ${{ secrets.pat_with_access }}
