name: Release Subtree

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REPO: ${{ github.repository }}
        PAYLOAD_PKEY: ${{ secrets.PKEY }}
        PAYLOAD_DIR: "a"
      with:
        repository: otton-faros/monorepo
        event: sync_tree
        github_pat: ${{ secrets.pat_with_access }}
